server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/motorbasedb
        username: server
        password: server_admin
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect