server:
    port: 8080


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/motorbasedb
        username: server
        password: server_admin
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always

    jpa:
#        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
#                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect